// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Amenity struct {
	ID            string  `json:"id"`
	Title         string  `json:"title"`
	Description   *string `json:"description"`
	Icon          string  `json:"icon"`
	ShowIfMissing bool    `json:"showIfMissing"`
	ShowInFilter  bool    `json:"showInFilter"`
}
